name: Keepalive
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  keepalive-job:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
