on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      ExtraVersion:
        description: 'Extra version string'
        required: false
        type: string

env:
  ADDON_ID: 3713
  API_KEY: ${{ secrets.APIKEY }}
  TZ: 'UTC'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Showcase JSON
        uses: actions/cache@v3
        with:
          key: showcase
          path: showcase.json
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: npm ci
      - name: Generate Showcase JSON
        run: node showcase
      - name: Publish Release Tracker addon
        run: node --no-experimental-fetch release-tracker